### YamlMime:PowershellCmdlet
summary: |-
  Verifies the keys and values in a session configuration file.
module: Microsoft.PowerShell.Core
notes: |-
  This cmdlet is only available on Windows platforms.
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: |-
    You can pipe a session configuration file path to `Test-PSSessionConfigurationFile`.
outputs:
- name: <xref href="System.Boolean" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Disable-PSSessionConfiguration
  href: Disable-PSSessionConfiguration.yml
- text: Enable-PSSessionConfiguration
  href: Enable-PSSessionConfiguration.yml
- text: Get-PSSessionConfiguration
  href: Get-PSSessionConfiguration.yml
- text: New-PSSessionConfigurationFile
  href: New-PSSessionConfigurationFile.yml
- text: New-PSSessionOption
  href: New-PSSessionOption.yml
- text: Register-PSSessionConfiguration
  href: Register-PSSessionConfiguration.yml
- text: Set-PSSessionConfiguration
  href: Set-PSSessionConfiguration.yml
- text: Test-PSSessionConfigurationFile
  href: Test-PSSessionConfigurationFile.yml
- text: Unregister-PSSessionConfiguration
  href: Unregister-PSSessionConfiguration.yml
- text: WSMan Provider
  href: ../Microsoft.WsMan.Management/About/about_WSMan_Provider.md
- text: about_Session_Configurations
  href: About/about_Session_Configurations.md
- text: about_Session_Configuration_Files
  href: About/about_Session_Configuration_Files.md
syntaxes:
- Test-PSSessionConfigurationFile [-Path] <String> [<CommonParameters>]
examples:
- title: 'Example 1: Test a session configuration file'
  code: |-
    Test-PSSessionConfigurationFile -Path "FullLanguage.pssc"

    True
  description: ""
  summary: ""
- title: 'Example 2: Test the session configuration file of a session configuration'
  code: |-
    Test-PSSessionConfigurationFile -Path (Get-PSSessionConfiguration -Name Restricted).ConfigFilePath
  description: ""
  summary: |+
    In this example, we test the configuration file used in the **Restricted** session configuration.
    The value of the **Path** parameter is the result of the `Get-PSSessionConfiguration` command that
    gets the **Restricted** session configuration. The path of the session configuration file is stored
    in the value of the **ConfigFilePath** property of the session configuration.

- title: 'Example 3: Test all session configuration files'
  code: |-
    function Test-AllConfigFiles
    {
        Get-PSSessionConfiguration | ForEach-Object {
            if ($_.ConfigFilePath) {
                $_.ConfigFilePath
                Test-PSSessionConfigurationFile -Verbose -Path $_.ConfigFilePath
            }
        }
    }
    Test-AllConfigFiles

    C:\WINDOWS\System32\WindowsPowerShell\v1.0\SessionConfig\Empty_6fd77bf6-e084-4372-bd8a-af3e207354d3.pssc
    True
    C:\WINDOWS\System32\WindowsPowerShell\v1.0\SessionConfig\Full_1e9cb265-dae0-4bd3-89a9-8338a47698a1.pssc
    VERBOSE: The member 'AliasDefinitions' must contain the required key 'Description'. Add the require key
    to the fileC:\WINDOWS\System32\WindowsPowerShell\v1.0\SessionConfig\Full_1e9cb265-dae0-4bd3-89a9-8338a47698a1.pssc.
    False
    C:\WINDOWS\System32\WindowsPowerShell\v1.0\SessionConfig\NoLanguage_0c115179-ff2a-4f66-a5eb-e56e5692ba22.pssc
    True
    C:\WINDOWS\System32\WindowsPowerShell\v1.0\SessionConfig\RestrictedLang_b6bd9474-0a6c-4e06-8722-c2c95bb10d3e.pssc
    True
    C:\WINDOWS\System32\WindowsPowerShell\v1.0\SessionConfig\RRS_3fb29420-2c87-46e5-a402-e21436331efc.pssc
    True
  description: |-
    The **ConfigFilePath** property of a session configuration contains the path of the session
    configuration file that is used in the session configuration, if any.

    If the value of the **ConfigFilePath** property is populated (is true), the command gets (prints)
    the **ConfigFilePath** property value. Then it uses the `Test-PSSessionConfigurationFile` cmdlet to
    test the file in the **ConfigFilePath** value. The **Verbose** parameter returns the file error when
    the file fails the test.
  summary: |+
    The function in this example tests all session configuration files on the local computer. The
    function uses the `Get-PSSessionConfiguration` cmdlet to get all session configurations. The code
    inside the `ForEach-Object` loop displays the file path and tests each of the session
    configurations.

parameters:
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Path
  isRequired: true
  description: |+
    Specifies the path and filename of a session configuration file (.pssc). If you omit the path, the
    default is the current folder. Wildcard characters are supported, but they must resolve to a single
    file. You can also pipe a session configuration file path to `Test-PSSessionConfigurationFile`.

  defaultValue: None
  acceptWildcardCharacters: true
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.PowerShell.Core.Test-PSSessionConfigurationFile
name: Test-PSSessionConfigurationFile
description: |-
  This cmdlet verifies that a session configuration file contains valid keys and the values are of the
  correct type. For enumerated values, the cmdlet verifies that the specified values are valid.

  The cmdlet returns `$True` if the file passes all tests and `$False` if it does not. To find any
  errors, use the **Verbose** parameter.

  `Test-PSSessionConfigurationFile` verifies the session configuration files, such as those created by
  the `New-PSSessionConfigurationFile` cmdlet. For information about session configurations, see
  [about_Session_Configurations](About/about_Session_Configurations.md). For information about session
  configuration files, see [about_Session_Configuration_Files](About/about_Session_Configuration_Files.md).

  This cmdlet was introduced in PowerShell 3.0.
metadata:
  external help file: System.Management.Automation.dll-Help.xml
  keywords: powershell,cmdlet
  Locale: en-US
  Module Name: Microsoft.PowerShell.Core
  ms.date: 03/28/2019
  online version: https://docs.microsoft.com/powershell/module/microsoft.powershell.core/test-pssessionconfigurationfile?view=powershell-7&WT.mc_id=ps-gethelp
  schema: 2.0.0
  title: Test-PSSessionConfigurationFile
