# This workflow verifies that an author submitting a pull request to the main
# branch to modify repository files is authorized to do so; only users with
# maintainer or admin rights may modify the actions or the workflow definitions.
name: Authorization
on:
  pull_request_target:
    branches:
      - main
    paths:
      - "*.yml"
      - .github/**
      - .localization-config
      - .openpublishing*
      - LICENSE*
      - reference/docfx.json
      - reference/mapping/**
      - tests/**
      - ThirdPartyNotices
      - tools/**
permissions:
  contents: read
jobs:
  Test:
    name: Check Repo File Permissions
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout Repository
        id: checkout_repo
        uses: actions/checkout@v4
      - name: Authorized to Modify Repo Files?
        uses: ./.github/actions/verification/authorization/v1
        with:
          token: ${{ github.token }}
          target: |
            path:
              *.yml
              .github/**
              .localization-config
              .openpublishing*
              LICENSE*
              reference/docfx.json
              reference/mapping/**
              tests/**
              ThirdPartyNotices
              tools/**
